In [1]:
import numpy as pd

In [2]:
list =[1,2,3,4]

In [6]:
pd.array(list)

array([1, 2, 3, 4])

In [9]:
import numpy as np
matrix =[[2,3,4],[3,5,6],[4,6,8]]
np.array(matrix)

array([[2, 3, 4],
       [3, 5, 6],
       [4, 6, 8]])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [18]:
np.linspace(2,2,5)


array([2., 2., 2., 2., 2.])

In [19]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [20]:
np.random.rand(2)

array([0.04305767, 0.99510764])

In [21]:
np.random.rand(100)

array([0.23469359, 0.04169339, 0.08301435, 0.10877877, 0.82240693,
       0.56294028, 0.33430556, 0.52702131, 0.70950939, 0.87649991,
       0.63710856, 0.5149436 , 0.90394714, 0.57615941, 0.52038036,
       0.77403987, 0.37995155, 0.41398428, 0.29669666, 0.82804371,
       0.32401718, 0.50698483, 0.29129682, 0.54802188, 0.86691081,
       0.82548713, 0.0061934 , 0.65180625, 0.19550699, 0.50771825,
       0.62625782, 0.67154565, 0.62439655, 0.94009349, 0.31817879,
       0.13735163, 0.71931469, 0.20565868, 0.55847906, 0.27971026,
       0.7668142 , 0.3789229 , 0.18703823, 0.11509124, 0.06260414,
       0.24611213, 0.48693007, 0.37740632, 0.39505866, 0.06069623,
       0.91076406, 0.78927707, 0.14462207, 0.71913397, 0.69236565,
       0.03427806, 0.08543208, 0.24663775, 0.56601582, 0.87383294,
       0.37399721, 0.29405179, 0.19434454, 0.73054755, 0.8947345 ,
       0.77373157, 0.06607395, 0.7548371 , 0.03706758, 0.6364609 ,
       0.29249682, 0.46451947, 0.00588941, 0.68357677, 0.96059

In [23]:
np.random.rand(2,3)

array([[0.51524443, 0.42105209, 0.46726214],
       [0.27569996, 0.90279381, 0.81696181]])

In [24]:
np.random.randn(2)


array([-1.73876702,  0.13641149])

In [26]:
np.random.randint(1,100)

65

In [27]:
np.random.randint(1,100,2)

array([55, 46])

In [28]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [30]:
arr=np.arange(25)


In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
matrix=np.random.rand(5,5)

In [33]:
matrix

array([[0.35474478, 0.23397231, 0.92441899, 0.40278333, 0.91314761],
       [0.69832861, 0.70970835, 0.44908617, 0.35982067, 0.35072367],
       [0.25444139, 0.35186681, 0.53494537, 0.09310225, 0.20541756],
       [0.88663625, 0.41623433, 0.38860609, 0.38642437, 0.20201279],
       [0.79735374, 0.66503399, 0.40677118, 0.35880739, 0.3073104 ]])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.max()

24

In [36]:
arr.min()

0

In [37]:
arr.argmax()

24

In [38]:
arr.argmin()

0

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape

<function ndarray.reshape>

In [42]:
arr.reshape(1,25).shape

(1, 25)

In [43]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr[9]

9

In [46]:
arr[1]

1

In [51]:
arr=np.arange(2,26)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [48]:
arr[3]

5

In [49]:
arr[1:8]

array([3, 4, 5, 6, 7, 8, 9])

In [52]:
arr.reshape(6,4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [56]:
arr[1:3]=100

In [57]:
arr

array([  2, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25])

In [58]:
arr.reshape(6,4)

array([[  2, 100, 100,   5],
       [  6,   7,   8,   9],
       [ 10,  11,  12,  13],
       [ 14,  15,  16,  17],
       [ 18,  19,  20,  21],
       [ 22,  23,  24,  25]])

In [59]:
arr[:]=99

In [60]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99])

In [61]:
arr.reshape(6,4)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [63]:
arr=np.arange(25)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
matrix=arr.reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
matrix[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [74]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 5,  5,  5, 13, 14],
       [ 5,  5,  5, 18, 19],
       [ 5,  5,  5, 23, 24]])

In [79]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [80]:
arr<8

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True,  True, False, False])

In [83]:
arr

3

In [88]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 5,  5,  5, 13, 14],
       [ 5,  5,  5, 18, 19],
       [ 5,  5,  5, 23, 24]])

In [90]:
matrix<6

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False]])

In [93]:
mtx=matrix<6

In [94]:
mtx

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False]])

In [96]:
matrix[matrix<6]

array([0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])