In [ ]:
import numpy as np
from scipy.linalg import svd

a=np.arange(1,26).reshape(5,5)
U,S,VT=svd(a)

In [ ]:
U

array([[-0.09359323, -0.76892152,  0.61130515,  0.0196316 , -0.16099879],
       [-0.24363203, -0.49055421, -0.5142169 , -0.45682855,  0.4763283 ],
       [-0.39367083, -0.2121869 , -0.3594458 ,  0.81870773, -0.02272392],
       [-0.54370962,  0.06618041, -0.18367831, -0.34545623, -0.73954194],
       [-0.69374842,  0.34454772,  0.44603585, -0.03605456,  0.44693633]])

In [ ]:
S

array([7.42540539e+01, 3.36681954e+00, 2.98266488e-15, 1.53916447e-15,
       2.08136977e-16])

In [10]:
VT

array([[-0.39262281, -0.41913118, -0.44563955, -0.47214793, -0.4986563 ],
       [ 0.667718  ,  0.35260325,  0.0374885 , -0.27762625, -0.592741  ],
       [ 0.5359956 , -0.50603463, -0.52349916,  0.42111979,  0.0724184 ],
       [-0.33541664,  0.36000724, -0.21070021,  0.68304527, -0.49693566],
       [ 0.01429645, -0.56064583,  0.69394096,  0.23686977, -0.38446135]])

In [11]:
U,S,VT=svd(a,full_matrices=True)

In [12]:
U

array([[-0.09359323, -0.76892152,  0.61130515,  0.0196316 , -0.16099879],
       [-0.24363203, -0.49055421, -0.5142169 , -0.45682855,  0.4763283 ],
       [-0.39367083, -0.2121869 , -0.3594458 ,  0.81870773, -0.02272392],
       [-0.54370962,  0.06618041, -0.18367831, -0.34545623, -0.73954194],
       [-0.69374842,  0.34454772,  0.44603585, -0.03605456,  0.44693633]])

In [13]:
U,S,VT=svd(a,full_matrices=False)
U

array([[-0.09359323, -0.76892152,  0.61130515,  0.0196316 , -0.16099879],
       [-0.24363203, -0.49055421, -0.5142169 , -0.45682855,  0.4763283 ],
       [-0.39367083, -0.2121869 , -0.3594458 ,  0.81870773, -0.02272392],
       [-0.54370962,  0.06618041, -0.18367831, -0.34545623, -0.73954194],
       [-0.69374842,  0.34454772,  0.44603585, -0.03605456,  0.44693633]])

In [ ]:
from numpy import diag
from numpy import dot
a=(U@np.diag(S)@VT)
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])